/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Lab1;

/**
 *
 * @author DolceVita
 */
public class HelloWorldGraphicalForExtra extends javax.swing.JFrame {

    /**
     * Creates new form HelloWorldGraphicalForExtra
     */
    public HelloWorldGraphicalForExtra() {
        initComponents();
        this.setTitle("Hello Extra GUI");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        englishCheck = new javax.swing.JCheckBox();
        deutschCheck = new javax.swing.JCheckBox();
        francaisCheck = new javax.swing.JCheckBox();
        englishLabel = new javax.swing.JLabel();
        deutschLabel = new javax.swing.JLabel();
        francaisLabel = new javax.swing.JLabel();
        beendenButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        englishCheck.setText("English");
        englishCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishCheckActionPerformed(evt);
            }
        });

        deutschCheck.setText("Deutsch");
        deutschCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deutschCheckActionPerformed(evt);
            }
        });

        francaisCheck.setText("Francais");
        francaisCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                francaisCheckActionPerformed(evt);
            }
        });

        beendenButton.setText("Beenden");
        beendenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beendenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(englishCheck)
                            .addComponent(deutschCheck)
                            .addComponent(francaisCheck))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(francaisLabel)
                            .addComponent(englishLabel)
                            .addComponent(deutschLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(beendenButton)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(englishCheck)
                    .addComponent(englishLabel))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deutschCheck)
                    .addComponent(deutschLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(francaisCheck)
                    .addComponent(francaisLabel))
                .addGap(43, 43, 43)
                .addComponent(beendenButton)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void englishCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishCheckActionPerformed
        // TODO add your handling code here:
        if(englishCheck.isSelected()){
            englishLabel.setText("Hello!");
        }
        else{
            englishLabel.setText("");
        }
    }//GEN-LAST:event_englishCheckActionPerformed

    private void deutschCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deutschCheckActionPerformed
        // TODO add your handling code here:
        if(deutschCheck.isSelected()){
            deutschLabel.setText("Guten Tag!");
        }
        else{
            deutschLabel.setText("");
        }
    }//GEN-LAST:event_deutschCheckActionPerformed

    private void francaisCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_francaisCheckActionPerformed
        // TODO add your handling code here:
        if(francaisCheck.isSelected()){
            francaisLabel.setText("Bonjour!");
        }
        else{
            francaisLabel.setText("");
        }
    }//GEN-LAST:event_francaisCheckActionPerformed

    private void beendenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beendenButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_beendenButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelloWorldGraphicalForExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelloWorldGraphicalForExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelloWorldGraphicalForExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelloWorldGraphicalForExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelloWorldGraphicalForExtra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beendenButton;
    private javax.swing.JCheckBox deutschCheck;
    private javax.swing.JLabel deutschLabel;
    private javax.swing.JCheckBox englishCheck;
    private javax.swing.JLabel englishLabel;
    private javax.swing.JCheckBox francaisCheck;
    private javax.swing.JLabel francaisLabel;
    // End of variables declaration//GEN-END:variables
}
